In [2]:
import pandas as pd
import os

In [4]:
path = '/mnt/HC_Volume_18315164/home-jupyter/jupyter-i-mihajlova/shared/homeworks/python_ds_miniprojects/5_subsid/subsid/'
# get all files with data
files = os.listdir(path)

In [8]:
# the good sequence of the columns in dataframe
good_columns = ['SUBS_ID', 'FILIAL_ID', 'PROD_ID', 'ACT_DTTM']

In [15]:
# change the sequence of columns in df and renemes it to lower, deletes rows with empty subs_id
def make_df(df):
    df = df.reindex(columns = good_columns)
    df = df.dropna(subset = ['SUBS_ID'])
    return df.rename(columns = lambda x: x.lower())

In [16]:
# create a big data frame with all info about sales

all_sales = pd.DataFrame([])
for i in range(1,4):
    df = pd.read_csv(path + files[i], sep = ';')
    df = make_df(df)
    all_sales = pd.concat([all_sales, df], ignore_index=True)

In [18]:
# adds a prefix id if necessary
def change_id(x):
    if x.startswith('id'):
        return x
    else:
        return 'id' + x

In [20]:
all_sales['subs_id'] = all_sales.subs_id.apply(change_id)

In [21]:
# the result
all_sales

     subs_id  filial_id  prod_id          act_dttm
0  id4651830          1     1954  20-03-2020 14:59
1  id7646509          5     6431  19-03-2020 13:00
2  id7412683          4     3313  22-03-2020 17:25
3  id5416547          3     1743  17-03-2020 10:17
4  id8362218          7     9879  05-03-2020 11:42
5  id2185490          2     3210  16-03-2020 16:28
6  id5764122          3     1499  18-03-2020 15:44
7  id7642700          6     3020  15-03-2020 14:21
8  id1374509          2     5677  17-03-2020 11:48

In [78]:
# load activation info
sales = pd.read_csv(path + files[0], sep = ';')

In [79]:
# rename the columns to lowercase
sales = sales.rename(columns = lambda x: x.lower())

In [80]:
# save the dates in format day-month-year hours-minuites
sales.start_dttm = pd.to_datetime(sales.start_dttm, format='%d-%m-%Y %H:%M')
sales.end_dttm = pd.to_datetime(sales.end_dttm, format='%d-%m-%Y %H:%M')

In [81]:
# calculate the activation time
sales['activation_time'] = sales.end_dttm - sales.start_dttm

In [83]:
# save all with long activation time
sales = sales[sales.activation_time > '5m']

In [84]:
# merge both tables
sales_info = all_sales.merge(sales, on='subs_id')

In [85]:
sales_info

,subs_id,filial_id,prod_id_x,act_dttm,prod_id_y,start_dttm,end_dttm,activation_time
0,id4651830,1,1954,20-03-2020 14:59,1954,2020-03-20 14:59:00,2020-12-01 00:00:00,255 days 09:01:00
1,id5416547,3,1743,17-03-2020 10:17,1743,2020-03-17 10:17:00,2020-03-25 11:00:00,8 days 00:43:00
2,id2185490,2,3210,16-03-2020 16:28,3210,2020-03-16 16:28:00,2020-12-01 00:00:00,259 days 07:32:00
3,id7642700,6,3020,15-03-2020 14:21,3020,2020-03-15 14:21:00,2020-03-15 23:42:00,0 days 09:21:00

In [91]:
', '.join(list(sales_info.sort_values('subs_id').subs_id))

'id2185490, id4651830, id5416547, id7642700'